### ISSUE TITLE
How to translate "kernel setup code" in Booting/README.md

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#108]
目前的翻译是内核设置代码，个人不是很满意这个翻译。

**Comment by hao-lee** [comment]
我以前曾经看过0.12的代码，setup这个过程从那时就有了，很古老，也很经典，我现在还记得当时的head.s、setup.s、main.c这三个经典的名字，虽然这么多年过去了发生了很大变动，但是这几个经典的单词已经成为标志了，所以我觉得可以不用翻译，直接说内核的setup阶段或流程。

**Comment by mudongliang** [comment]
好吧
