### ISSUE TITLE
申请翻译13.3

### ISSUE THREAD

**Issue by hao-lee** [MintCN/linux-insides-zh#110]

**Comment by xinqiu** [comment]
同样，参考翻译说明哦

**Comment by hao-lee** [comment]
@xinqiu 没有问题~

**Comment by hao-lee** [comment]
类似 Happy Hacking! 这样的话保留原文如何，我觉得翻译不出原文的感觉。

**Comment by xinqiu** [comment]
那样估计最好单独搭建一个展示的网站，通过js切换只有中文或者中英文对照，确实会很好，但是感觉暂时不好实现啊😔

**Comment by xinqiu** [comment]
那样估计最好单独搭建一个展示的网站，通过js切换只有中文或者中英文对照，确实会很好，但是感觉暂时不好实现啊😔

**Comment by hao-lee** [comment]
这是文章结尾的一句话，我想了很久不知道怎么翻译合适 :sweat_smile: 
“愉快的探索吧”，这样似乎也不合适

**Comment by xinqiu** [comment]
哦哦，抱歉> <，这种口语话的就随意吧🤔

**Comment by hao-lee** [comment]
:smirk:
