### ISSUE TITLE
申请翻译6.5、6.6

### ISSUE THREAD

**Issue by e1001925** [MintCN/linux-insides-zh#119]

**Comment by xinqiu** [comment]
参考翻译说明提交pr就可以了> <

**Comment by hdl** [comment]
@e1001925 请问能帮否帮你分担一节？

**Comment by e1001925** [comment]
@hdl 抱歉最近超级忙，可以，请你选一节剩下的告知我，我会周末翻译

**Comment by hdl** [comment]
好的，我开始翻译6.5

**Comment by lifangwang** [comment]
@hdl @e1001925 ,  我建议你们提交PR，我看到readme的状态6.5/6.6没有人认领，但是看到issue里面你已们经在翻译了，不知道实际情况如何？

**Comment by xinqiu** [comment]
@lifangwang 大大说的很对，翻译前记得修改readme

**Comment by mudongliang** [comment]
我已经按照这里的讨论大致分了一下章节，如果有问题，可以@我进行更改。

**Comment by e1001925** [comment]
@mudongliang  看邮件记录hdl是要翻译6.5，所以我这边已经做了一部分6.6了，这样分配有误吧？

**Comment by mudongliang** [comment]
抱歉，你说的对。是我搞错了，马上进行更改。

**Comment by mudongliang** [comment]
已经更换过来了。

**Comment by mudongliang** [comment]
根据回收原则 #135 ，该issue 将被回收，如需要翻译对应部分，请重新申请。
