### ISSUE TITLE
URL 检查

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#127]
@xinqiu ，最近有空吗？我们一起把所有的链接 check 一下，如何？

**Comment by mudongliang** [comment]
1. 无效的链接
2. 该使用中文版，但是还是使用英文版的链接
3. 内核源码的 Github 链接;
。。。

**Comment by xinqiu** [comment]
可能不一定有时间，正在复习考研中 ┭┮﹏┭┮

**Comment by mudongliang** [comment]
考研更重要，你好好复习！

**Comment by mudongliang** [comment]
这个URL问题上游已经进行更新，我们需要把上游的修改patch 到中文翻译中
