### ISSUE TITLE
翻译回收机制讨论

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#135]
@xinqiu 我想把现在所有的翻译请求进行整理，然后将时间过长的issue 进行回收。另外，讨论一下回收进制，比如说，多长时间进行回收。如果你最近很忙的话，我可以先暂定一种回收机制。

**Comment by xinqiu** [comment]
非常抱歉> <，我感觉已经好久一段时间没有帮忙这个项目了。确实我们应该将一些长时间没有更新的issue暂时关闭，留给其他人来接手。我最近尽量抽出时间来配合你进行回收吧。

**Comment by mudongliang** [comment]
你最近比较忙的话，我可以先来，不过我只有周六，周日的时间来做。

**Comment by xinqiu** [comment]
那我也周末的时候来帮忙吧

**Comment by mudongliang** [comment]
我觉得以三个月为期，如果届时没有任何更新的话，就需要关闭 对应的 Issue， 已经清空对应的README 表格中的内容。

**Comment by mudongliang** [comment]
三个月只是一个大致时间，可以根据提交issue 的contributor的实际时间来进行微调

**Comment by mudongliang** [comment]
@xinqiu , 如果星期天有空的话，我们来讨论一下翻译回收的问题，如何？

**Comment by xinqiu** [comment]
好的呀
