### ISSUE TITLE
申请翻译 Cgroups 章节

### ISSUE THREAD

**Issue by tjm-1990** [MintCN/linux-insides-zh#136]
申请翻译 Cgroups 章节，但是 README.md 中没有该章节，可以翻译吗？

**Comment by mudongliang** [comment]
我会把 cgroups 章节的英文加到我们的库里面，然后你pull 一下，之后提交PR申请翻译该部分。

**Comment by mudongliang** [comment]
@tjm-1990 您好，我已经将cgroups部分的内容加到了当前库中，请另外开一个Issue来申请你对应的小节，虽然目前只有一个小节。确认要翻译的小节之后，你需要提交对应的PR来”占坑“， 同时注意一下Issue 中的过期回收问题。
