### ISSUE TITLE
申请翻译Concepts

### ISSUE THREAD

**Issue by up2wing** [MintCN/linux-insides-zh#137]
大家好，申请翻译Concepts一章 9.1、9.2、9.3。
之前申请过，后来忙就忘记了，sorry。
现在已经翻完了，新开个issue提交吧。谢谢！

**Comment by mudongliang** [comment]
收到 PR，会尽快 review

**Comment by up2wing** [comment]
好的。thx @mudongliang

**Comment by mudongliang** [comment]
@up2wing 我已经提出一些 review 的意见，你可能需要根据我的意见在你的译文上进行修改。

**Comment by mudongliang** [comment]
#138

**Comment by mudongliang** [comment]
PR 已经被 merge 了，接下来请修改 README 中的状态 @up2wing
