### ISSUE TITLE
申请翻译3,2~3,8

### ISSUE THREAD

**Issue by up2wing** [MintCN/linux-insides-zh#139]
大家好，继续申请翻译3,2~3,8。

**Comment by mudongliang** [comment]
你可以一个章节，一个章节的提交 PR 吗？这样比较方便我们校验。

**Comment by up2wing** [comment]
OK，我尽快把已经翻好的整理一下先提交。最近有点忙，进度慢了，sorry。

**Comment by mudongliang** [comment]
由于大部分文件名字都被修改，所以请您重新 fork 最新版本的库，然后再次提交翻译申请。非常抱歉给您带来的不便。
