### ISSUE TITLE
URL  校对

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#144]
Todo List (后续会进行更改或追加)：
- 把所有译文中含有 “0xax” 的链接统统修改为当前库中的链接或者当前库的 gitbook 的链接;
- Sync the links that the upstream has modified. It is easy to ignore.

**Comment by xinqiu** [comment]
第一个我之前做过一遍了，现在只要简单检查，看看哪些没改过来就可以了
