### ISSUE TITLE
Gitbook 更新

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#149]
Gitbook 需要进行更新，因为我加入了上游的一些新章节。

**Comment by mudongliang** [comment]
既然你比较忙，在你比较忙的期间，你可以主要负责 Gitbook 的更新。虽然我对 Gitbook 的工作机制有点不太熟悉，但是这里面的工作应该不大，很多部分都可以自动更新的。我就先 take care 本库的 PR 和Issue。

**Comment by xinqiu** [comment]
好的，我也会负责一些PR和Issues的

**Comment by mudongliang** [comment]
这里面包括将一些上游的含有 0xAX 或者 0xax 关键字的 gitbook 链接更新到中文的 gitbook。我刚才 "grep -R ..." 看了一下，里面还是有很多的。特别是有一句，每个文件里面都有，“**请注意英语不是我的母语，对此带来的不便，我很抱歉。如果你发现了任何错误，都可以给我发 PR 到[linux-insides](https://github.com/0xAX/linux-insides)。**.”

**Comment by mudongliang** [comment]
这一句话，我们当时讨论的结果是什么，我都有点给忘了！

**Comment by xinqiu** [comment]
我也忘了，其实我个人的想法是，这一句话就统一不要翻译，直接用‘若有相关问题，请提交issue’之类的，不管是在我们的repo还是原repo都可以进行文章内容的讨论

**Comment by mudongliang** [comment]
你可不可以统一一下这句话？就按你刚才说的，不过要指出，英文原文问题，找上游 repo - linux-insides 提交 issue；翻译问题，在下游 repo - linux-insides-zh 中提交 issue。同时，注意更新 Gitbook 相关链接。

**Comment by xinqiu** [comment]
那就改成“若有相关问题，请提交issue。英文原文问题，找上游 repo - linux-insides 提交 issue；翻译问题，在下游 repo - linux-insides-zh 中提交 issue。”这句话放在README里面？同时在翻译约定里添上，这句话默认不翻译？毕竟原作者一开始是更新在博客里的，所以每篇都喜欢加这些，现在我觉得作为整本书，只需要封面做了解释，每篇文章里没有这些，可能阅读体验更好一点。

**Comment by mudongliang** [comment]
我觉得可以。不过你那句话要加上链接。

**Comment by xinqiu** [comment]
好的

**Comment by mudongliang** [comment]
You need to add new chapters(Cgroups) to Gitbook. I see the new chapters are not synced to Gitbook.

**Comment by xinqiu** [comment]
OK
