### ISSUE TITLE
change translation status of 15.1

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#154]
@tjm-1990 , don't forget to modify the translation status of 15.1 to "one commit" with 8 digits.

**Comment by mudongliang** [comment]
@tjm-1990

**Comment by tjm-1990** [comment]
多谢，已提交 PR：[#159](https://github.com/MintCN/linux-insides-zh/pull/159)

**Comment by mudongliang** [comment]
我发现你这个英文原文之后有一些 commit 来修改 URL，你能不能把这部分修改添加到译文中？

**Comment by tjm-1990** [comment]
PR 已提交。[#159](https://github.com/MintCN/linux-insides-zh/pull/159)
