### ISSUE TITLE
申请翻译Memory management部分

### ISSUE THREAD

**Issue by choleraehyq** [MintCN/linux-insides-zh#16]

**Comment by xinqiu** [comment]
非常感谢你能来参与这个项目。你只需要翻译好了提一个pr就可以了。

**Comment by mudongliang** [comment]
@xinqiu 在认领翻译之后，请将主页上对应部分的翻译者进行添加。

**Comment by mudongliang** [comment]
另外，在对应PR未merge之前，这个issue不可以close。

**Comment by xinqiu** [comment]
好的

**Comment by mudongliang** [comment]
@choleraehyq 十分感谢你前两小节的 PR ，请再接再厉。

**Comment by mudongliang** [comment]
根据回收原则 #135 ，该issue 将被回收，如需要翻译对应部分，请重新申请。
