### ISSUE TITLE
已翻译内容错别字

### ISSUE THREAD

**Issue by xiaobogaga** [MintCN/linux-insides-zh#160]
链接：https://xinqiu.gitbooks.io/linux-insides-cn/content/Booting/linux-bootstrap-1.html
第一段， “底层是**如果**工作的，程序是如何在电脑上运行的” 应该为：
“底层是**如何**工作的，程序是如何在电脑上运行的”

**Comment by mudongliang** [comment]
@xiaobogaga 请提交 PR，我会在 review 之后 merge 的。

**Comment by xiaobogaga** [comment]
好的。

**Comment by mudongliang** [comment]
#162
