### ISSUE TITLE
maybe one bug in Github markdown 

### ISSUE THREAD

**Issue by mudongliang** [MintCN/linux-insides-zh#163]
SUMMARY.md 中的 markdown 渲染貌似除了点问题，很奇怪。但是 gitbook 中没有问题。
```
* [内存管理](MM/README.md)
    * [内存块](MM/linux-mm-1.md)
    * [固定映射地址和 ioremap](MM/linux-mm-2.md)
    * [kmemcheck](MM/linux-mm-3.md)
* [Cgroups](Cgroups/README.md)
    * [控制组简介](Cgroups/cgroups1.md)
```

![screenshot from 2017-10-10 15-15-52](https://user-images.githubusercontent.com/6214861/31406043-ee6fabe6-adcd-11e7-89f5-b5597c81324e.png)

**Comment by mudongliang** [comment]
@xinqiu 你能不能看看这个问题是怎么回事，如果确定是 Github 的问题，给他们发个邮件询问一下。

**Comment by xinqiu** [comment]
好的，我这几天抽空看一下

**Comment by xinqiu** [comment]
fixed it.
