### ISSUE TITLE
申请翻译 5.1 章节

### ISSUE THREAD

**Issue by luoxiaobing** [MintCN/linux-insides-zh#168]
申请翻译第5.1章节

**Comment by mudongliang** [comment]
请提交 PR 修改翻译状态。相见 README 翻译流程

**Comment by mudongliang** [comment]
另外尽量一个章节一个章节申请，这样既方便翻译，又不会造成校验的负担。

**Comment by mudongliang** [comment]
由于大部分文件名字都被修改，所以请您重新 fork 最新版本的库，然后再次提交翻译申请。非常抱歉给您带来的不便。
