### ISSUE TITLE
1.5章节中的代码问题

### ISSUE THREAD

**Issue by losemyheaven** [MintCN/linux-insides-zh#180]
我不知道这个问题是否应该在这里提出，如应在其他地方提出，请指正。

1.5章节中，描述被压缩的内核会被复制到另外一个地方进行解压缩，作者引用了内核源码
```
    pushq    %rsi
    leaq    (_bss-8)(%rip), %rsi
    leaq    (_bss-8)(%rbx), %rdi
    movq    $_bss, %rcx
    shrq    $3, %rcx
    std
    rep    movsq
    cld
    popq    %rsi
```
我没能理解为什么两条leaq指令中需要对_bss进行减8操作
如有知悉，请指教。

**Comment by mudongliang** [comment]
这个我还真不知道，你可能需要去上游发一个 issue 问问。如果有人知道，请帮忙回答一下。

**Comment by SilenceWang123** [comment]
这里有详解https://luzeshu.com/blog/rip-relative-addressing

**Comment by losemyheaven** [comment]
@SilenceWang123 这个文章讲解了rip相对寻址的问题，但是并没有解释为什么要-8
我昨天发到kernelnewbies 里面，得到了答案，在此粘贴一下
```
leaq	(_bss-8)(%rip), %rsi
leaq	(_bss-8)(%rbx), %rdi
movq	$_bss /* - $startup_32 */, %rcx
shrq	$3, %rcx
std
rep	movsq
cld
```
The movsq instruction copys 8 bytes each time and for the first time it will copy [_bss-8, _bss) to the new location. If we don't minus 8, the data in [_bss, _bss+8) will also be copied on the first execution of movsq. Obviously, we don't want to copy the bss section.

Regards,
Hao Lee
