### ISSUE TITLE
申请翻译SysCall部分

### ISSUE THREAD

**Issue by qianmoke** [MintCN/linux-insides-zh#19]

**Comment by xinqiu** [comment]
感谢您的参与，翻译好了，请提交pr就可以了。

**Comment by chinano1** [comment]
trans syscall

**Comment by xinqiu** [comment]
@chinano1 SysCall已经有@qianmoke 翻译了，你可以选择翻译其他部分或者商量一下SysCall的翻译部分？

**Comment by mudongliang** [comment]
@xinqiu 我们可以把readme的syscall部分展开到具体每一个小节， @chinano1 , @qianmoke 商量好好了，可以提交PR修改README！

**Comment by xinqiu** [comment]
好的

**Comment by mudongliang** [comment]
@qianmoke 我虽然把你的PR给merge了，但是你还没有翻译完。请再接再厉！谢谢！
