### ISSUE TITLE
申请翻译3.4

### ISSUE THREAD

**Issue by Newester** [MintCN/linux-insides-zh#194]
3.3被人动过了？

**Comment by Newester** [comment]
只能clone不能push啊，是不是需要权限？@mudongliang

**Comment by mudongliang** [comment]
你好，只有管理者才能 push commits to Github。其他contributors 只能通过PR（Pull Request）提交修改。

**Comment by Newester** [comment]
不好意思，没有参与过开源项目，没用过PR，以后会按照规则进行章节翻译的@mudongliang

**Comment by mudongliang** [comment]
Do you still want to translate such section? If not, I will close this issue and unlock 3.4.

**Comment by Albertchamberlain** [comment]
I will translate 3.3
