### ISSUE TITLE
第一章节的图片无法显示

### ISSUE THREAD

**Issue by BlackHole1** [MintCN/linux-insides-zh#204]
地址: [从引导加载程序内核](https://xinqiu.gitbooks.io/linux-insides-cn/content/Booting/linux-bootstrap-1.html)

其中的图片目前都无法访问

**Comment by mudongliang** [comment]
这个感觉好奇怪。Github 的markdown 显示没有问题，不知道gitbook为什么会出现这种问题。

**Comment by BlackHole1** [comment]
估计是限制了referer

**Comment by mudongliang** [comment]
那就先不管这个问题了
