### ISSUE TITLE
感觉应该是“揭秘”而非“揭密”

### ISSUE THREAD

**Issue by guozesheng** [MintCN/linux-insides-zh#206]
好像通常写作“揭秘”和“解密”。
“揭秘”指揭开秘密。研究、探索客观自然界的奥秘或客观历史的疑云。
“解密”指解开保密者本来主观上本来不想让更多人知道的秘密。
个人观点，仅供参考。

**Comment by mudongliang** [comment]
我觉得有道理。@xinqiu,你觉得呢？

**Comment by xinqiu** [comment]
以前没考虑过这个问题，感觉确实应该修改为揭秘

**Comment by mudongliang** [comment]
I've modified it. Thanks for your advice.
