### ISSUE TITLE
Booting/linux-bootstrap-1.md 中 “在内核被引导入内存后，内存使用情况将入下表所示：”，“入”字错误

### ISSUE THREAD

**Issue by xianfengting** [MintCN/linux-insides-zh#207]
[Booting/linux-bootstrap-1.md](https://github.com/MintCN/linux-insides-zh/blob/master/Booting/linux-bootstrap-1.md) 文件中，
> 通过阅读 kernel boot protocol，在内核被引导入内存后，内存使用情况将入下表所示：

一段中，“入”字错误，应改为：

> 通过阅读 kernel boot protocol，在内核被引导入内存后，内存使用情况将如下表所示：

**Comment by mudongliang** [comment]
Thanks for your issue. I've modified the typo. I think you could directly pull request next time.
