### ISSUE TITLE
1.0 error

### ISSUE THREAD

**Issue by void0red** [MintCN/linux-insides-zh#217]
First of all, the kernel ensures that the ds and es segment registers point to the same
address. Next, it clears the direction flag using the cld instruction:
```
movw %ds, %ax
movw %ax, %es
cld
```

**cld not sti**

**Comment by mudongliang** [comment]
Please provide more information. Do you mean some errors in one chapter?

**Comment by void0red** [comment]
https://github.com/MintCN/linux-insides-zh/blob/44ad5ac5fb82c9038048e27209a784d077f122d8/Booting/linux-bootstrap-1.md?plain=1#L344

it seems to be `cld` not `sti`
see at:
1. https://github.com/0xAX/linux-insides/blob/2cceabdd31d8a11c188cb03f5d943eb5d57f27c2/Booting/linux-bootstrap-1.md?plain=1#L435
2. https://elixir.bootlin.com/linux/latest/source/arch/x86/boot/header.S#L592

**Comment by mudongliang** [comment]
应该是上游更新了，但是下游的翻译还用之前的版本。

**Comment by mudongliang** [comment]
你如果有时间的话，可以提交一个PR来更新一下

**Comment by mudongliang** [comment]
Fixed in commit ad33bb1
