### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by StepfenShawn** [MintCN/linux-insides-zh#218]
你好，首先感谢你们的翻译。
我发现了一个小问题: 第一章里图片无法显示
![image](https://user-images.githubusercontent.com/44727245/76833197-e0292580-6865-11ea-82d3-8b379b51d984.png)

**Comment by xinqiu** [comment]
上游仓库换成了本地图片，这里因为还是沿用的外链导致图片加载错误。

**Comment by stepfencurryxiao** [comment]
能否在这个repo中创建一个images文件去存放这些图片，这样图片应该就可以显示出来了

**Comment by xinqiu** [comment]
确实可以这样的，刚才手动替换了第一章的图片url

**Comment by dian-yu-luo** [comment]
所以剩下的还准备换吗？

**Comment by xinqiu** [comment]
> 所以剩下的还准备换吗？

有空我来换一下

**Comment by mudongliang** [comment]
这个issue目前还有update吗？
