### ISSUE TITLE
想请教个和翻译无关的问题

### ISSUE THREAD

**Issue by wjzhangcsu** [MintCN/linux-insides-zh#219]
Linux本身有很多特性，这些特性不系统学习很难掌握，比如零拷贝，copy-on-write,请问这方面知识有没有书籍或者资料学习呢？

**Comment by xinqiu** [comment]
或者可以学习一下MIT 6.828?

**Comment by 769344359** [comment]
<深入Linux内核架构>
cow 这里面就有介绍吧

https://www.zhihu.com/question/19606660
