### ISSUE TITLE
申请翻译 Chapter 5.Timers and time management

### ISSUE THREAD

**Issue by icecoobe** [MintCN/linux-insides-zh#22]
我对Chapter 3中断 && 5 时钟均感兴趣，这里先申请翻译短一些的第五章，如果届时中断这个大部头还没有人来领取，我会再申请～

O(∩_∩)O谢谢

**Comment by xinqiu** [comment]
感谢您的参与，你只需先fork项目，然后翻译好了提一个pr就可以了。

**Comment by icecoobe** [comment]
got it, thank you!
