### ISSUE TITLE
内核引导过程. 第一部分. 设置堆栈小节 ss寄存器的值有问题

### ISSUE THREAD

**Issue by Willendless** [MintCN/linux-insides-zh#227]
ss寄存器的值应当为0x1000，文中为0x10000.

**Comment by xinqiu** [comment]
> ss寄存器的值应当为0x1000，文中为0x10000.

我确认了一下原文，似乎也是0x10000
https://github.com/0xAX/linux-insides/blob/master/Booting/linux-bootstrap-1.md
