### ISSUE TITLE
中断和中断处理第九节的Tasklets部分的翻译错误

### ISSUE THREAD

**Issue by yfhu99** [MintCN/linux-insides-zh#233]
翻译原文：和软中断不同的是，同一类型的`tasklets`可以在同一时间运行于不同的处理器上。

英文原文：and unlike `softirqs`, tasklets that have the same type _cannot_ be run on multiple processors at a time. 

这里，同一类型tasklets应该是不能同时运行在多个处理器上。

**Comment by xinqiu** [comment]
感谢发现，我来修改一下> <
