### ISSUE TITLE
这个项目还在维护吗？

### ISSUE THREAD

**Issue by ysun** [MintCN/linux-insides-zh#241]
@mudongliang @xinqiu 
好像最近的code change是半年前的，项目目前还在坚持吗？

**Comment by xinqiu** [comment]
最近维护的有点少了，但我还会努力维护的，欢迎参与翻译工作~

**Comment by ysun** [comment]
> 最近维护的有点少了，但我还会努力维护的，欢迎参与翻译工作~

刚意识到，你可以merge code :smile:  厉害了 @xinqiu

**Comment by dian-yu-luo** [comment]
有讨论群吗,有些地方看不懂,希望找人问一下

**Comment by xinqiu** [comment]
> 有讨论群吗,有些地方看不懂,希望找人问一下

目前没有讨论群> <

**Comment by mudongliang** [comment]
我来建议讨论群吧，只是不知道大家倾向使用qq还是微信或者其他交流工具？

**Comment by dian-yu-luo** [comment]
tg

**Comment by lyjnb** [comment]
好像网页版的https://xinqiu.gitbooks.io/linux-insides-cn/content/Initialization/linux-initialization-5.html

**Comment by zhaoshouhang** [comment]
tg+1

**Comment by xinqiu** [comment]
https://t.me/linux_insides

**Comment by YalandHong** [comment]
> 有讨论群吗,有些地方看不懂,希望找人问一下

其实我觉得开个issue或者启用Discussion似乎也行。telegram的话，总感觉不方便搜索

**Comment by mudongliang** [comment]
大家可以直接使用上游的google group

**Comment by mudongliang** [comment]
鉴于这个issue的title容易让大家产生误解，所以我们将关闭这个issue
