### ISSUE TITLE
申请翻译1-2

### ISSUE THREAD

**Issue by hailincai** [MintCN/linux-insides-zh#27]

**Comment by hailincai** [comment]
I redo the "PR" for apply for translating this chapter, please check. The pull request comes from my branch "chap1_2_trans_pr". Also the translation is complete, the pull request comes from my branch "chap1_2".

Thanks

**Comment by mudongliang** [comment]
Thanks! I and @xinqiu will check it!

**Comment by xinqiu** [comment]
I proposed some advice, please check it. Thanks.

**Comment by hailincai** [comment]
Today I review the translation, I find several typo in the file. I fix them all, please have a look again.

**Comment by hailincai** [comment]
The chapter has been merged, so close the issue

**Comment by hailincai** [comment]
The chapter has been merged, so close the issue
