### ISSUE TITLE
申请翻译 1-4

### ISSUE THREAD

**Issue by zmj1316** [MintCN/linux-insides-zh#41]

**Comment by xinqiu** [comment]
参考https://github.com/MintCN/linux-insides-zh/blob/master/CONTRIBUTING.md 提交PR就可以了

**Comment by mudongliang** [comment]
#45

**Comment by mudongliang** [comment]
I have updated the translation status in [commit 63d71d](https://github.com/MintCN/linux-insides-zh/commit/63d71daf810a454a4961d36347475edc7722adf4)
