### ISSUE TITLE
本书在Gitbook上线了

### ISSUE THREAD

**Issue by xinqiu** [MintCN/linux-insides-zh#5]
[点击访问](https://www.gitbook.com/book/xinqiu/linux-insides-cn/details)可以查看本书已翻译的部分。

**Comment by mudongliang** [comment]
:+1:

**Comment by hao-lee** [comment]
我觉得翻译项目有一个很难解决的问题：如果英文版对某章节进行了修正和更新，如何保证中文版会及时追踪到。

**Comment by xinqiu** [comment]
@hao-lee 只能考虑出第一版和第二版这种办法

**Comment by mudongliang** [comment]
我们可以给每一个文件一个对应于上游 commit， 保证在这个 commit 时刻所有的内容都是一致的，然后缓步推进。
