### ISSUE TITLE
申请翻译2.4-2.10

### ISSUE THREAD

**Issue by bjwrkj** [MintCN/linux-insides-zh#66]
已修改README.md Status且提交;

**Comment by mudongliang** [comment]
已经 merge 了，之后请提交 进一步的PR，尽量使用少量的 commit，最好是一个文件一个commit，谢谢！

**Comment by xinqiu** [comment]
请问你还在翻译么？ @bjwrkj

**Comment by mudongliang** [comment]
已翻译完成

**Comment by bjwrkj** [comment]
不好意思，我最近会上传；  @xinqiu

**Comment by mudongliang** [comment]
根据回收原则 #135 ，该issue 将被回收，如需要翻译对应部分，请重新申请。
