### ISSUE TITLE
请问这是什么语法？

### ISSUE THREAD

**Issue by levonhe** [MintCN/linux-insides-zh#69]
.section ".reset"
    .code16
.globl  reset_vector
reset_vector:
    .byte  0xe9
    .int   _start - ( . + 2 )
    ...

**Comment by xinqiu** [comment]
这是汇编代码

**Comment by mudongliang** [comment]
Actually this is AT&T assembly semantics, not Intel assembly semantics.

**Comment by levonhe** [comment]
谢谢。。。
