### ISSUE TITLE
申请翻译13.2

### ISSUE THREAD

**Issue by zmj1316** [MintCN/linux-insides-zh#75]
已发 PR ，请问是按照本repo里面的翻译还是原作者那个？

**Comment by xinqiu** [comment]
原作者的应该和这个内容是一样的

**Comment by zmj1316** [comment]
好的，了解了

xinqiu <notifications@github.com>于2016年8月5日周五 下午12:09写道：

**Comment by xinqiu** [comment]
感谢你的参与👍

**Comment by mudongliang** [comment]
@zmj1316 我在认领规则里面加上了一条。因为fork的时间比较早，上游的英文更新比较快，所以会出现本库中的英文版本比较旧。如果你可以先提交一下 commit 来推送最新的英文，就最好了。
![image](https://cloud.githubusercontent.com/assets/6214861/18075782/11bb4d3a-6e46-11e6-96f6-f578ca400675.png)

**Comment by zmj1316** [comment]
了解

Dongliang Mu <notifications@github.com>于2016年8月30日周二 下午12:11写道：

**Comment by mudongliang** [comment]
已完成
